//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportStars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart_items
    {
        public int cart_items_id { get; set; }
        public int cart_items_quantity { get; set; }
        public int product_id { get; set; }
        public Nullable<System.DateTime> cart_items_insertdate { get; set; }
        public decimal cart_items_unit_price { get; set; }
        public Nullable<decimal> cart_items_subtotal { get; set; }
        public Nullable<int> order_id { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual product product { get; set; }
    }
}
