//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportStars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orders()
        {
            this.cart_items = new HashSet<cart_items>();
        }
    
        public int order_id { get; set; }
        public string shipper_type { get; set; }
        public Nullable<decimal> order_total { get; set; }
        public Nullable<int> order_amount { get; set; }
        public string order_name { get; set; }
        public string order_address { get; set; }
        public string order_zipcode { get; set; }
        public string order_city { get; set; }
        public string order_phone { get; set; }
        public Nullable<int> order_nif { get; set; }
        public Nullable<System.DateTime> order_datetime { get; set; }
        public string order_user { get; set; }
        public string payment_type { get; set; }
        public Nullable<int> order_country { get; set; }
        public string order_status { get; set; }
        public Nullable<System.DateTime> order_datetime_finish { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart_items> cart_items { get; set; }
        public virtual country country { get; set; }
    }
}
