using System.ComponentModel.DataAnnotations;
//------------------------------------------------------------------------------
// <auto-generated>
//[Required(ErrorMessage = "Please enter name"), MaxLength(50)]
//public string product_name { get; set; }
//[Required(ErrorMessage = "Please enter a price")]
//[RegularExpression(@"^\d+(\.\d{1,2})?$", ErrorMessage = "Invalid price")]
//[Range(0, 9999999999999999.99, ErrorMessage = "Out of range")]
//public decimal product_price { get; set; }
//[RegularExpression(@"^[0-9]\d*$", ErrorMessage = "Invalid Weight")]
//[Range(0, 100000, ErrorMessage = "Out of range")]
//public Nullable<float> product_weight { get; set; }
//[DataType(DataType.Text), MaxLength(10)]
//public string product_letter_size { get; set; }
//[RegularExpression(@"^[0-9]\d*$", ErrorMessage = "Invalid number size")]
//public Nullable<float> product_number_size { get; set; }
//[RegularExpression(@"^[0-9]\d*$", ErrorMessage = "Invalid quantity")]
//public int product_qtd { get; set; }
//[DataType(DataType.Text), MaxLength(500)]
//public string product_comment { get; set; }
//public Nullable<System.DateTime> product_datetime { get; set; }
//public int product_id { get; set; }
//[RegularExpression(@"^[0-9]\d*$", ErrorMessage = "Invalid Year")]
//[Range(1900, 2021, ErrorMessage = "Out of range")]
//public Nullable<int> product_year { get; set; }
//[DataType(DataType.Text), MaxLength(20, ErrorMessage = "Out of lenght")]
//public string product_type { get; set; }
//[DataType(DataType.Text), MaxLength(30, ErrorMessage = "Out of lenght")]
//public string brands_name { get; set; }
//[DataType(DataType.Text), MaxLength(50, ErrorMessage = "Out of lenght")]
//public string product_player_name { get; set; }
//[DataType(DataType.Text), MaxLength(40, ErrorMessage = "Out of lenght")]
//public string competition_name { get; set; }
//[DataType(DataType.Text), MaxLength(40, ErrorMessage = "Out of lenght")]
//public string team_name { get; set; }
//[DataType(DataType.Text), MaxLength(30, ErrorMessage = "Out of lenght")]
//public string subcategory_name { get; set; }
//[Required(ErrorMessage = "Please enter a status"), MaxLength(20)]
//public string product_status { get; set; }
//[DataType(DataType.Text), MaxLength(250, ErrorMessage = "Out of lenght")]
//public string product_mainimage { get; set; }
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportStars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.cart_items = new HashSet<cart_items>();
            this.images = new HashSet<images>();
        }

        [Required(ErrorMessage = "Please enter name"),MaxLength(50)]
        public string product_name { get; set; }
        [Required(ErrorMessage = "Please enter a price")]
        [RegularExpression(@"^\d+(\.\d{1,2})?$", ErrorMessage = "Invalid price")]
        [Range(0,9999999999999999.99, ErrorMessage = "Out of range")]
        public decimal product_price { get; set; }
        [RegularExpression(@"^[0-9]\d*$", ErrorMessage = "Invalid Weight")]
        [Range(0,100000, ErrorMessage = "Out of range")]
        public Nullable<float> product_weight { get; set; }
        [DataType(DataType.Text), MaxLength(10)]
        public string product_letter_size { get; set; }
        [RegularExpression(@"^[0-9]\d*$", ErrorMessage = "Invalid number size")]
        public Nullable<float> product_number_size { get; set; }
        [RegularExpression(@"^[0-9]\d*$", ErrorMessage = "Invalid quantity")]
        public int product_qtd { get; set; }
        [DataType(DataType.Text),MaxLength(500)]
        public string product_comment { get; set; }
        public Nullable<System.DateTime> product_datetime { get; set; }
        public int product_id { get; set; }
        [RegularExpression(@"^[0-9]\d*$", ErrorMessage = "Invalid Year")]
        [Range(1900,2021,ErrorMessage = "Out of range")]
        public Nullable<int> product_year { get; set; }
        [DataType(DataType.Text), MaxLength(20,ErrorMessage = "Out of lenght")]
        public string product_type { get; set; }
        [DataType(DataType.Text), MaxLength(30, ErrorMessage = "Out of lenght")]
        public string brands_name { get; set; }
        [DataType(DataType.Text), MaxLength(50, ErrorMessage = "Out of lenght")]
        public string product_player_name { get; set; }
        [DataType(DataType.Text), MaxLength(40, ErrorMessage = "Out of lenght")]
        public string competition_name { get; set; }
        [DataType(DataType.Text), MaxLength(40, ErrorMessage = "Out of lenght")]
        public string team_name { get; set; }
        [DataType(DataType.Text), MaxLength(30, ErrorMessage = "Out of lenght")]
        public string subcategory_name { get; set; }
        [Required(ErrorMessage = "Please enter a status"), MaxLength(20)]
        public string product_status { get; set; }
        [DataType(DataType.Text), MaxLength(250,ErrorMessage = "Out of lenght")]
        public string product_mainimage { get; set; }
    
        public virtual brands brands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart_items> cart_items { get; set; }
        public virtual competition competition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<images> images { get; set; }
        public virtual subcategory subcategory { get; set; }
        public virtual team team { get; set; }
    }
}
