//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportStars.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class finalbootstrap_dbEntities : DbContext
    {
        public finalbootstrap_dbEntities()
            : base("name=finalbootstrap_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<brands> brands { get; set; }
        public virtual DbSet<cart_items> cart_items { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<competition> competition { get; set; }
        public virtual DbSet<continent> continent { get; set; }
        public virtual DbSet<country> country { get; set; }
        public virtual DbSet<images> images { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<sport> sport { get; set; }
        public virtual DbSet<subcategory> subcategory { get; set; }
        public virtual DbSet<team> team { get; set; }
    }
}
